version: "3"
services:
  redis:
   image: redis
  db:
   image: postgres:9.4
   environment:
    POSTGRES_HOST_AUTH_METHOD: "trust"
  vote:
   image: rishi88221/dock-compose:voting-app
   ports: 
    - 5000:80
  worker:
   image: rishi88221/dock-compose:result-app
  result:
   image: rishi88221/dock-compose:answer-app
   ports:
    - 5001:80



